/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceSelectRouteImport } from './routes/workspace-select'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTenantRoomRouteImport } from './routes/_authenticated.tenant.room'
import { Route as AuthenticatedTenantPaymentsRouteImport } from './routes/_authenticated.tenant.payments'
import { Route as AuthenticatedTenantLaundryRouteImport } from './routes/_authenticated.tenant.laundry'
import { Route as AuthenticatedTenantDocumentsRouteImport } from './routes/_authenticated.tenant.documents'
import { Route as AuthenticatedTenantDashboardRouteImport } from './routes/_authenticated.tenant.dashboard'
import { Route as AuthenticatedTenantComplaintsRouteImport } from './routes/_authenticated.tenant.complaints'
import { Route as AuthenticatedSuperAdminSettingsRouteImport } from './routes/_authenticated.super-admin.settings'
import { Route as AuthenticatedSuperAdminRevenueRouteImport } from './routes/_authenticated.super-admin.revenue'
import { Route as AuthenticatedSuperAdminReportsRouteImport } from './routes/_authenticated.super-admin.reports'
import { Route as AuthenticatedSuperAdminPropertiesRouteImport } from './routes/_authenticated.super-admin.properties'
import { Route as AuthenticatedSuperAdminPlansRouteImport } from './routes/_authenticated.super-admin.plans'
import { Route as AuthenticatedSuperAdminOwnersRouteImport } from './routes/_authenticated.super-admin.owners'
import { Route as AuthenticatedSuperAdminDashboardRouteImport } from './routes/_authenticated.super-admin.dashboard'
import { Route as AuthenticatedSuperAdminAuditRouteImport } from './routes/_authenticated.super-admin.audit'
import { Route as AuthenticatedSuperAdminAnnouncementsRouteImport } from './routes/_authenticated.super-admin.announcements'
import { Route as AuthenticatedStaffDashboardRouteImport } from './routes/_authenticated.staff.dashboard'
import { Route as AuthenticatedOwnerTenantsRouteImport } from './routes/_authenticated.owner.tenants'
import { Route as AuthenticatedOwnerStaffRouteImport } from './routes/_authenticated.owner.staff'
import { Route as AuthenticatedOwnerSettingsRouteImport } from './routes/_authenticated.owner.settings'
import { Route as AuthenticatedOwnerRoomsRouteImport } from './routes/_authenticated.owner.rooms'
import { Route as AuthenticatedOwnerReportsRouteImport } from './routes/_authenticated.owner.reports'
import { Route as AuthenticatedOwnerPropertiesRouteImport } from './routes/_authenticated.owner.properties'
import { Route as AuthenticatedOwnerPaymentsRouteImport } from './routes/_authenticated.owner.payments'
import { Route as AuthenticatedOwnerDashboardRouteImport } from './routes/_authenticated.owner.dashboard'
import { Route as AuthenticatedOwnerComplaintsRouteImport } from './routes/_authenticated.owner.complaints'

const WorkspaceSelectRoute = WorkspaceSelectRouteImport.update({
  id: '/workspace-select',
  path: '/workspace-select',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTenantRoomRoute = AuthenticatedTenantRoomRouteImport.update({
  id: '/tenant/room',
  path: '/tenant/room',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTenantPaymentsRoute =
  AuthenticatedTenantPaymentsRouteImport.update({
    id: '/tenant/payments',
    path: '/tenant/payments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTenantLaundryRoute =
  AuthenticatedTenantLaundryRouteImport.update({
    id: '/tenant/laundry',
    path: '/tenant/laundry',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTenantDocumentsRoute =
  AuthenticatedTenantDocumentsRouteImport.update({
    id: '/tenant/documents',
    path: '/tenant/documents',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTenantDashboardRoute =
  AuthenticatedTenantDashboardRouteImport.update({
    id: '/tenant/dashboard',
    path: '/tenant/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTenantComplaintsRoute =
  AuthenticatedTenantComplaintsRouteImport.update({
    id: '/tenant/complaints',
    path: '/tenant/complaints',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSuperAdminSettingsRoute =
  AuthenticatedSuperAdminSettingsRouteImport.update({
    id: '/super-admin/settings',
    path: '/super-admin/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSuperAdminRevenueRoute =
  AuthenticatedSuperAdminRevenueRouteImport.update({
    id: '/super-admin/revenue',
    path: '/super-admin/revenue',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSuperAdminReportsRoute =
  AuthenticatedSuperAdminReportsRouteImport.update({
    id: '/super-admin/reports',
    path: '/super-admin/reports',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSuperAdminPropertiesRoute =
  AuthenticatedSuperAdminPropertiesRouteImport.update({
    id: '/super-admin/properties',
    path: '/super-admin/properties',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSuperAdminPlansRoute =
  AuthenticatedSuperAdminPlansRouteImport.update({
    id: '/super-admin/plans',
    path: '/super-admin/plans',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSuperAdminOwnersRoute =
  AuthenticatedSuperAdminOwnersRouteImport.update({
    id: '/super-admin/owners',
    path: '/super-admin/owners',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSuperAdminDashboardRoute =
  AuthenticatedSuperAdminDashboardRouteImport.update({
    id: '/super-admin/dashboard',
    path: '/super-admin/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSuperAdminAuditRoute =
  AuthenticatedSuperAdminAuditRouteImport.update({
    id: '/super-admin/audit',
    path: '/super-admin/audit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSuperAdminAnnouncementsRoute =
  AuthenticatedSuperAdminAnnouncementsRouteImport.update({
    id: '/super-admin/announcements',
    path: '/super-admin/announcements',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStaffDashboardRoute =
  AuthenticatedStaffDashboardRouteImport.update({
    id: '/staff/dashboard',
    path: '/staff/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOwnerTenantsRoute =
  AuthenticatedOwnerTenantsRouteImport.update({
    id: '/owner/tenants',
    path: '/owner/tenants',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOwnerStaffRoute = AuthenticatedOwnerStaffRouteImport.update({
  id: '/owner/staff',
  path: '/owner/staff',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOwnerSettingsRoute =
  AuthenticatedOwnerSettingsRouteImport.update({
    id: '/owner/settings',
    path: '/owner/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOwnerRoomsRoute = AuthenticatedOwnerRoomsRouteImport.update({
  id: '/owner/rooms',
  path: '/owner/rooms',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOwnerReportsRoute =
  AuthenticatedOwnerReportsRouteImport.update({
    id: '/owner/reports',
    path: '/owner/reports',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOwnerPropertiesRoute =
  AuthenticatedOwnerPropertiesRouteImport.update({
    id: '/owner/properties',
    path: '/owner/properties',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOwnerPaymentsRoute =
  AuthenticatedOwnerPaymentsRouteImport.update({
    id: '/owner/payments',
    path: '/owner/payments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOwnerDashboardRoute =
  AuthenticatedOwnerDashboardRouteImport.update({
    id: '/owner/dashboard',
    path: '/owner/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOwnerComplaintsRoute =
  AuthenticatedOwnerComplaintsRouteImport.update({
    id: '/owner/complaints',
    path: '/owner/complaints',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/workspace-select': typeof WorkspaceSelectRoute
  '/owner/complaints': typeof AuthenticatedOwnerComplaintsRoute
  '/owner/dashboard': typeof AuthenticatedOwnerDashboardRoute
  '/owner/payments': typeof AuthenticatedOwnerPaymentsRoute
  '/owner/properties': typeof AuthenticatedOwnerPropertiesRoute
  '/owner/reports': typeof AuthenticatedOwnerReportsRoute
  '/owner/rooms': typeof AuthenticatedOwnerRoomsRoute
  '/owner/settings': typeof AuthenticatedOwnerSettingsRoute
  '/owner/staff': typeof AuthenticatedOwnerStaffRoute
  '/owner/tenants': typeof AuthenticatedOwnerTenantsRoute
  '/staff/dashboard': typeof AuthenticatedStaffDashboardRoute
  '/super-admin/announcements': typeof AuthenticatedSuperAdminAnnouncementsRoute
  '/super-admin/audit': typeof AuthenticatedSuperAdminAuditRoute
  '/super-admin/dashboard': typeof AuthenticatedSuperAdminDashboardRoute
  '/super-admin/owners': typeof AuthenticatedSuperAdminOwnersRoute
  '/super-admin/plans': typeof AuthenticatedSuperAdminPlansRoute
  '/super-admin/properties': typeof AuthenticatedSuperAdminPropertiesRoute
  '/super-admin/reports': typeof AuthenticatedSuperAdminReportsRoute
  '/super-admin/revenue': typeof AuthenticatedSuperAdminRevenueRoute
  '/super-admin/settings': typeof AuthenticatedSuperAdminSettingsRoute
  '/tenant/complaints': typeof AuthenticatedTenantComplaintsRoute
  '/tenant/dashboard': typeof AuthenticatedTenantDashboardRoute
  '/tenant/documents': typeof AuthenticatedTenantDocumentsRoute
  '/tenant/laundry': typeof AuthenticatedTenantLaundryRoute
  '/tenant/payments': typeof AuthenticatedTenantPaymentsRoute
  '/tenant/room': typeof AuthenticatedTenantRoomRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/workspace-select': typeof WorkspaceSelectRoute
  '/owner/complaints': typeof AuthenticatedOwnerComplaintsRoute
  '/owner/dashboard': typeof AuthenticatedOwnerDashboardRoute
  '/owner/payments': typeof AuthenticatedOwnerPaymentsRoute
  '/owner/properties': typeof AuthenticatedOwnerPropertiesRoute
  '/owner/reports': typeof AuthenticatedOwnerReportsRoute
  '/owner/rooms': typeof AuthenticatedOwnerRoomsRoute
  '/owner/settings': typeof AuthenticatedOwnerSettingsRoute
  '/owner/staff': typeof AuthenticatedOwnerStaffRoute
  '/owner/tenants': typeof AuthenticatedOwnerTenantsRoute
  '/staff/dashboard': typeof AuthenticatedStaffDashboardRoute
  '/super-admin/announcements': typeof AuthenticatedSuperAdminAnnouncementsRoute
  '/super-admin/audit': typeof AuthenticatedSuperAdminAuditRoute
  '/super-admin/dashboard': typeof AuthenticatedSuperAdminDashboardRoute
  '/super-admin/owners': typeof AuthenticatedSuperAdminOwnersRoute
  '/super-admin/plans': typeof AuthenticatedSuperAdminPlansRoute
  '/super-admin/properties': typeof AuthenticatedSuperAdminPropertiesRoute
  '/super-admin/reports': typeof AuthenticatedSuperAdminReportsRoute
  '/super-admin/revenue': typeof AuthenticatedSuperAdminRevenueRoute
  '/super-admin/settings': typeof AuthenticatedSuperAdminSettingsRoute
  '/tenant/complaints': typeof AuthenticatedTenantComplaintsRoute
  '/tenant/dashboard': typeof AuthenticatedTenantDashboardRoute
  '/tenant/documents': typeof AuthenticatedTenantDocumentsRoute
  '/tenant/laundry': typeof AuthenticatedTenantLaundryRoute
  '/tenant/payments': typeof AuthenticatedTenantPaymentsRoute
  '/tenant/room': typeof AuthenticatedTenantRoomRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/workspace-select': typeof WorkspaceSelectRoute
  '/_authenticated/owner/complaints': typeof AuthenticatedOwnerComplaintsRoute
  '/_authenticated/owner/dashboard': typeof AuthenticatedOwnerDashboardRoute
  '/_authenticated/owner/payments': typeof AuthenticatedOwnerPaymentsRoute
  '/_authenticated/owner/properties': typeof AuthenticatedOwnerPropertiesRoute
  '/_authenticated/owner/reports': typeof AuthenticatedOwnerReportsRoute
  '/_authenticated/owner/rooms': typeof AuthenticatedOwnerRoomsRoute
  '/_authenticated/owner/settings': typeof AuthenticatedOwnerSettingsRoute
  '/_authenticated/owner/staff': typeof AuthenticatedOwnerStaffRoute
  '/_authenticated/owner/tenants': typeof AuthenticatedOwnerTenantsRoute
  '/_authenticated/staff/dashboard': typeof AuthenticatedStaffDashboardRoute
  '/_authenticated/super-admin/announcements': typeof AuthenticatedSuperAdminAnnouncementsRoute
  '/_authenticated/super-admin/audit': typeof AuthenticatedSuperAdminAuditRoute
  '/_authenticated/super-admin/dashboard': typeof AuthenticatedSuperAdminDashboardRoute
  '/_authenticated/super-admin/owners': typeof AuthenticatedSuperAdminOwnersRoute
  '/_authenticated/super-admin/plans': typeof AuthenticatedSuperAdminPlansRoute
  '/_authenticated/super-admin/properties': typeof AuthenticatedSuperAdminPropertiesRoute
  '/_authenticated/super-admin/reports': typeof AuthenticatedSuperAdminReportsRoute
  '/_authenticated/super-admin/revenue': typeof AuthenticatedSuperAdminRevenueRoute
  '/_authenticated/super-admin/settings': typeof AuthenticatedSuperAdminSettingsRoute
  '/_authenticated/tenant/complaints': typeof AuthenticatedTenantComplaintsRoute
  '/_authenticated/tenant/dashboard': typeof AuthenticatedTenantDashboardRoute
  '/_authenticated/tenant/documents': typeof AuthenticatedTenantDocumentsRoute
  '/_authenticated/tenant/laundry': typeof AuthenticatedTenantLaundryRoute
  '/_authenticated/tenant/payments': typeof AuthenticatedTenantPaymentsRoute
  '/_authenticated/tenant/room': typeof AuthenticatedTenantRoomRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/unauthorized'
    | '/workspace-select'
    | '/owner/complaints'
    | '/owner/dashboard'
    | '/owner/payments'
    | '/owner/properties'
    | '/owner/reports'
    | '/owner/rooms'
    | '/owner/settings'
    | '/owner/staff'
    | '/owner/tenants'
    | '/staff/dashboard'
    | '/super-admin/announcements'
    | '/super-admin/audit'
    | '/super-admin/dashboard'
    | '/super-admin/owners'
    | '/super-admin/plans'
    | '/super-admin/properties'
    | '/super-admin/reports'
    | '/super-admin/revenue'
    | '/super-admin/settings'
    | '/tenant/complaints'
    | '/tenant/dashboard'
    | '/tenant/documents'
    | '/tenant/laundry'
    | '/tenant/payments'
    | '/tenant/room'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/unauthorized'
    | '/workspace-select'
    | '/owner/complaints'
    | '/owner/dashboard'
    | '/owner/payments'
    | '/owner/properties'
    | '/owner/reports'
    | '/owner/rooms'
    | '/owner/settings'
    | '/owner/staff'
    | '/owner/tenants'
    | '/staff/dashboard'
    | '/super-admin/announcements'
    | '/super-admin/audit'
    | '/super-admin/dashboard'
    | '/super-admin/owners'
    | '/super-admin/plans'
    | '/super-admin/properties'
    | '/super-admin/reports'
    | '/super-admin/revenue'
    | '/super-admin/settings'
    | '/tenant/complaints'
    | '/tenant/dashboard'
    | '/tenant/documents'
    | '/tenant/laundry'
    | '/tenant/payments'
    | '/tenant/room'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/unauthorized'
    | '/workspace-select'
    | '/_authenticated/owner/complaints'
    | '/_authenticated/owner/dashboard'
    | '/_authenticated/owner/payments'
    | '/_authenticated/owner/properties'
    | '/_authenticated/owner/reports'
    | '/_authenticated/owner/rooms'
    | '/_authenticated/owner/settings'
    | '/_authenticated/owner/staff'
    | '/_authenticated/owner/tenants'
    | '/_authenticated/staff/dashboard'
    | '/_authenticated/super-admin/announcements'
    | '/_authenticated/super-admin/audit'
    | '/_authenticated/super-admin/dashboard'
    | '/_authenticated/super-admin/owners'
    | '/_authenticated/super-admin/plans'
    | '/_authenticated/super-admin/properties'
    | '/_authenticated/super-admin/reports'
    | '/_authenticated/super-admin/revenue'
    | '/_authenticated/super-admin/settings'
    | '/_authenticated/tenant/complaints'
    | '/_authenticated/tenant/dashboard'
    | '/_authenticated/tenant/documents'
    | '/_authenticated/tenant/laundry'
    | '/_authenticated/tenant/payments'
    | '/_authenticated/tenant/room'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  WorkspaceSelectRoute: typeof WorkspaceSelectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace-select': {
      id: '/workspace-select'
      path: '/workspace-select'
      fullPath: '/workspace-select'
      preLoaderRoute: typeof WorkspaceSelectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tenant/room': {
      id: '/_authenticated/tenant/room'
      path: '/tenant/room'
      fullPath: '/tenant/room'
      preLoaderRoute: typeof AuthenticatedTenantRoomRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tenant/payments': {
      id: '/_authenticated/tenant/payments'
      path: '/tenant/payments'
      fullPath: '/tenant/payments'
      preLoaderRoute: typeof AuthenticatedTenantPaymentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tenant/laundry': {
      id: '/_authenticated/tenant/laundry'
      path: '/tenant/laundry'
      fullPath: '/tenant/laundry'
      preLoaderRoute: typeof AuthenticatedTenantLaundryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tenant/documents': {
      id: '/_authenticated/tenant/documents'
      path: '/tenant/documents'
      fullPath: '/tenant/documents'
      preLoaderRoute: typeof AuthenticatedTenantDocumentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tenant/dashboard': {
      id: '/_authenticated/tenant/dashboard'
      path: '/tenant/dashboard'
      fullPath: '/tenant/dashboard'
      preLoaderRoute: typeof AuthenticatedTenantDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tenant/complaints': {
      id: '/_authenticated/tenant/complaints'
      path: '/tenant/complaints'
      fullPath: '/tenant/complaints'
      preLoaderRoute: typeof AuthenticatedTenantComplaintsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/super-admin/settings': {
      id: '/_authenticated/super-admin/settings'
      path: '/super-admin/settings'
      fullPath: '/super-admin/settings'
      preLoaderRoute: typeof AuthenticatedSuperAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/super-admin/revenue': {
      id: '/_authenticated/super-admin/revenue'
      path: '/super-admin/revenue'
      fullPath: '/super-admin/revenue'
      preLoaderRoute: typeof AuthenticatedSuperAdminRevenueRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/super-admin/reports': {
      id: '/_authenticated/super-admin/reports'
      path: '/super-admin/reports'
      fullPath: '/super-admin/reports'
      preLoaderRoute: typeof AuthenticatedSuperAdminReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/super-admin/properties': {
      id: '/_authenticated/super-admin/properties'
      path: '/super-admin/properties'
      fullPath: '/super-admin/properties'
      preLoaderRoute: typeof AuthenticatedSuperAdminPropertiesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/super-admin/plans': {
      id: '/_authenticated/super-admin/plans'
      path: '/super-admin/plans'
      fullPath: '/super-admin/plans'
      preLoaderRoute: typeof AuthenticatedSuperAdminPlansRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/super-admin/owners': {
      id: '/_authenticated/super-admin/owners'
      path: '/super-admin/owners'
      fullPath: '/super-admin/owners'
      preLoaderRoute: typeof AuthenticatedSuperAdminOwnersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/super-admin/dashboard': {
      id: '/_authenticated/super-admin/dashboard'
      path: '/super-admin/dashboard'
      fullPath: '/super-admin/dashboard'
      preLoaderRoute: typeof AuthenticatedSuperAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/super-admin/audit': {
      id: '/_authenticated/super-admin/audit'
      path: '/super-admin/audit'
      fullPath: '/super-admin/audit'
      preLoaderRoute: typeof AuthenticatedSuperAdminAuditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/super-admin/announcements': {
      id: '/_authenticated/super-admin/announcements'
      path: '/super-admin/announcements'
      fullPath: '/super-admin/announcements'
      preLoaderRoute: typeof AuthenticatedSuperAdminAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/staff/dashboard': {
      id: '/_authenticated/staff/dashboard'
      path: '/staff/dashboard'
      fullPath: '/staff/dashboard'
      preLoaderRoute: typeof AuthenticatedStaffDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/owner/tenants': {
      id: '/_authenticated/owner/tenants'
      path: '/owner/tenants'
      fullPath: '/owner/tenants'
      preLoaderRoute: typeof AuthenticatedOwnerTenantsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/owner/staff': {
      id: '/_authenticated/owner/staff'
      path: '/owner/staff'
      fullPath: '/owner/staff'
      preLoaderRoute: typeof AuthenticatedOwnerStaffRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/owner/settings': {
      id: '/_authenticated/owner/settings'
      path: '/owner/settings'
      fullPath: '/owner/settings'
      preLoaderRoute: typeof AuthenticatedOwnerSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/owner/rooms': {
      id: '/_authenticated/owner/rooms'
      path: '/owner/rooms'
      fullPath: '/owner/rooms'
      preLoaderRoute: typeof AuthenticatedOwnerRoomsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/owner/reports': {
      id: '/_authenticated/owner/reports'
      path: '/owner/reports'
      fullPath: '/owner/reports'
      preLoaderRoute: typeof AuthenticatedOwnerReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/owner/properties': {
      id: '/_authenticated/owner/properties'
      path: '/owner/properties'
      fullPath: '/owner/properties'
      preLoaderRoute: typeof AuthenticatedOwnerPropertiesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/owner/payments': {
      id: '/_authenticated/owner/payments'
      path: '/owner/payments'
      fullPath: '/owner/payments'
      preLoaderRoute: typeof AuthenticatedOwnerPaymentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/owner/dashboard': {
      id: '/_authenticated/owner/dashboard'
      path: '/owner/dashboard'
      fullPath: '/owner/dashboard'
      preLoaderRoute: typeof AuthenticatedOwnerDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/owner/complaints': {
      id: '/_authenticated/owner/complaints'
      path: '/owner/complaints'
      fullPath: '/owner/complaints'
      preLoaderRoute: typeof AuthenticatedOwnerComplaintsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedOwnerComplaintsRoute: typeof AuthenticatedOwnerComplaintsRoute
  AuthenticatedOwnerDashboardRoute: typeof AuthenticatedOwnerDashboardRoute
  AuthenticatedOwnerPaymentsRoute: typeof AuthenticatedOwnerPaymentsRoute
  AuthenticatedOwnerPropertiesRoute: typeof AuthenticatedOwnerPropertiesRoute
  AuthenticatedOwnerReportsRoute: typeof AuthenticatedOwnerReportsRoute
  AuthenticatedOwnerRoomsRoute: typeof AuthenticatedOwnerRoomsRoute
  AuthenticatedOwnerSettingsRoute: typeof AuthenticatedOwnerSettingsRoute
  AuthenticatedOwnerStaffRoute: typeof AuthenticatedOwnerStaffRoute
  AuthenticatedOwnerTenantsRoute: typeof AuthenticatedOwnerTenantsRoute
  AuthenticatedStaffDashboardRoute: typeof AuthenticatedStaffDashboardRoute
  AuthenticatedSuperAdminAnnouncementsRoute: typeof AuthenticatedSuperAdminAnnouncementsRoute
  AuthenticatedSuperAdminAuditRoute: typeof AuthenticatedSuperAdminAuditRoute
  AuthenticatedSuperAdminDashboardRoute: typeof AuthenticatedSuperAdminDashboardRoute
  AuthenticatedSuperAdminOwnersRoute: typeof AuthenticatedSuperAdminOwnersRoute
  AuthenticatedSuperAdminPlansRoute: typeof AuthenticatedSuperAdminPlansRoute
  AuthenticatedSuperAdminPropertiesRoute: typeof AuthenticatedSuperAdminPropertiesRoute
  AuthenticatedSuperAdminReportsRoute: typeof AuthenticatedSuperAdminReportsRoute
  AuthenticatedSuperAdminRevenueRoute: typeof AuthenticatedSuperAdminRevenueRoute
  AuthenticatedSuperAdminSettingsRoute: typeof AuthenticatedSuperAdminSettingsRoute
  AuthenticatedTenantComplaintsRoute: typeof AuthenticatedTenantComplaintsRoute
  AuthenticatedTenantDashboardRoute: typeof AuthenticatedTenantDashboardRoute
  AuthenticatedTenantDocumentsRoute: typeof AuthenticatedTenantDocumentsRoute
  AuthenticatedTenantLaundryRoute: typeof AuthenticatedTenantLaundryRoute
  AuthenticatedTenantPaymentsRoute: typeof AuthenticatedTenantPaymentsRoute
  AuthenticatedTenantRoomRoute: typeof AuthenticatedTenantRoomRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedOwnerComplaintsRoute: AuthenticatedOwnerComplaintsRoute,
  AuthenticatedOwnerDashboardRoute: AuthenticatedOwnerDashboardRoute,
  AuthenticatedOwnerPaymentsRoute: AuthenticatedOwnerPaymentsRoute,
  AuthenticatedOwnerPropertiesRoute: AuthenticatedOwnerPropertiesRoute,
  AuthenticatedOwnerReportsRoute: AuthenticatedOwnerReportsRoute,
  AuthenticatedOwnerRoomsRoute: AuthenticatedOwnerRoomsRoute,
  AuthenticatedOwnerSettingsRoute: AuthenticatedOwnerSettingsRoute,
  AuthenticatedOwnerStaffRoute: AuthenticatedOwnerStaffRoute,
  AuthenticatedOwnerTenantsRoute: AuthenticatedOwnerTenantsRoute,
  AuthenticatedStaffDashboardRoute: AuthenticatedStaffDashboardRoute,
  AuthenticatedSuperAdminAnnouncementsRoute:
    AuthenticatedSuperAdminAnnouncementsRoute,
  AuthenticatedSuperAdminAuditRoute: AuthenticatedSuperAdminAuditRoute,
  AuthenticatedSuperAdminDashboardRoute: AuthenticatedSuperAdminDashboardRoute,
  AuthenticatedSuperAdminOwnersRoute: AuthenticatedSuperAdminOwnersRoute,
  AuthenticatedSuperAdminPlansRoute: AuthenticatedSuperAdminPlansRoute,
  AuthenticatedSuperAdminPropertiesRoute:
    AuthenticatedSuperAdminPropertiesRoute,
  AuthenticatedSuperAdminReportsRoute: AuthenticatedSuperAdminReportsRoute,
  AuthenticatedSuperAdminRevenueRoute: AuthenticatedSuperAdminRevenueRoute,
  AuthenticatedSuperAdminSettingsRoute: AuthenticatedSuperAdminSettingsRoute,
  AuthenticatedTenantComplaintsRoute: AuthenticatedTenantComplaintsRoute,
  AuthenticatedTenantDashboardRoute: AuthenticatedTenantDashboardRoute,
  AuthenticatedTenantDocumentsRoute: AuthenticatedTenantDocumentsRoute,
  AuthenticatedTenantLaundryRoute: AuthenticatedTenantLaundryRoute,
  AuthenticatedTenantPaymentsRoute: AuthenticatedTenantPaymentsRoute,
  AuthenticatedTenantRoomRoute: AuthenticatedTenantRoomRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  WorkspaceSelectRoute: WorkspaceSelectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
